apiVersion: "v1"
kind: "Pod"
spec:
  tolerations:
    - key: type
      effect: NoSchedule
      operator: Equal
      value: jenkins-builder
  nodeSelector:
    type: jenkins-builder
  containers:
  - args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
    image: "gcr.io/sandbox-csuite/csuite/builder-node:develop"
    imagePullPolicy: "Always"
    name: "node"
    resources:
      limits:
        memory: "16Gi"
        cpu: "3"
      requests:
        memory: "5Gi"
        cpu: "3"
        ephemeral-storage: 2Gi
    tty: true
    securityContext:
      privileged: false
      runAsUser: 1000 # user jenkins
      fsGroup: 112 # group docker
  - args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
    image: "sonarsource/sonar-scanner-cli:5"
    imagePullPolicy: "Always"
    env:
      - name: SONAR_HOST_URL
        value: https://sonar.tools.mycooperlsuite.io
    name: "sonar-scanner"
    resources:
      limits:
        memory: "4Gi"
      requests:
        memory: "1Gi"
        cpu: "2"
        ephemeral-storage: 10Mi
    tty: true
    securityContext:
      privileged: false
      runAsUser: 1000 # user jenkins
      fsGroup: 112 # group docker
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.3.0-debug #image debug pour avoir un shell
    imagePullPolicy: Always
    args:
      - cat
    command:
      - /busybox/sh
      - -c
    tty: true
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/kaniko-secret.json
    volumeMounts:
      - name: kaniko-secret
        mountPath: /secret
    resources:
      limits:
        cpu: "4"
        memory: 3Gi
      requests:
        cpu: 500m
        memory: 1Gi
        ephemeral-storage: 5Gi
    securityContext:
      privileged: false
  - name: crane
    image: gcr.io/sandbox-csuite/csuite/gcrane:develop
    imagePullPolicy: Always
    args:
      - cat
    command:
      - /busybox/sh
      - -c
    tty: true
    volumeMounts:
    - mountPath: /home/jenkins/.config/gcloud
      name: jenkins-gcloud-serviceaccount
    securityContext:
      privileged: false
      runAsUser: 1000 # user jenkins
      fsGroup: 112 # group docker
  - name: "gcloud-kubectl"
    args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
    image: "gcr.io/sandbox-csuite/csuite/gcloud-kubectl:develop"
    imagePullPolicy: "Always"
    resources:
      limits:
        memory: "3Gi"
        cpu: "5"
      requests:
        memory: "1Gi"
        cpu: "500m"
        ephemeral-storage: 10Mi
    tty: true
    volumeMounts:
    - mountPath: /home/jenkins/.kube
      name: kubectl-cache
  volumes:
  - emptyDir:
      medium: Memory
    name: tmpfs
  - emptyDir:
      medium: Memory
    name: kubectl-cache
  - name: kaniko-secret
    secret:
      secretName: kaniko-secret
  - secret:
      secretName: jenkins-gcloud-serviceaccount
      items:
      - key: jenkins-serviceaccount.json
        mode: 511
        path: application_default_credentials.json
    name: jenkins-gcloud-serviceaccount
